services:
  postgres:
    image: postgres:latest
    container_name: streamflix_db
    environment:
      POSTGRES_DB: streamflix      
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: student@student.com
      PGADMIN_DEFAULT_PASSWORD: student
    ports:
      - "8123:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
